### ISSUE TITLE
ECONNREFUSED localhost:8000

### ISSUE THREAD

**Issue by EwanValentine** [RuBAN-GT/sample-appsync-offline#1]
I've more or less mirrored what you have in this example repo, and I'm seeing errors connecting to DynamoDB. I'm seeing: ECONNREFUSED localhost:8000. It fires up serverless offline still, but doesn't start appsync offline. 

Did you encounter any issues like this?

**Comment by RuBAN-GT** [comment]
@EwanValentine, Hello! Did you use yarn instead npm (emulator dependencies require it)?

I tried to start this sample project and all are booting without any problems.
```
Serverless: Compiling with Typescript...
Serverless: Using local tsconfig.json
Serverless: Typescript compiled.
Serverless: Watching typescript files...
Serverless: AppSync started: http://localhost:62222/graphql
Dynamodb Local Started, Visit: http://localhost:8000/shell
Serverless: Starting Offline: dev/us-east-1.

Serverless: Routes for graphql:
Serverless: (none)

Serverless: Offline listening on http://localhost:3000
```

But after it I sent request and got 500 error for:
```graphql
query MyQuery {
  sample
}
```
May be appsync emulator has new changes or bugs? For my project I forked it and fixed many bugs and made improvements, because it's good package, but, unfortunately, unfinished. You can do it too and try to debug all hooks for severless. Also, for better information, You can set `NODE_DEBUG=*` for output debug-level logs from sls.

**Comment by EwanValentine** [comment]
Okay cool, thank you!!
